theme: minima
title: JRC Portfolio
author: Antonio Vivaldi
description: this a github pages sorta site that supposedly presents very interesting dev projects that would kinda build up to a sorta portfolio thingy. Yup.
